### ISSUE TITLE
Should this library be used with marqo cloud? 

### ISSUE THREAD

**Issue by brianfeister** [ganeshdipdumbare/marqo-go#10]
I'm sure I can just append my API key to the request header for all calls, but before I go further with such a hack, I wanted to ask if it's the goal of this library to be able to include an API key when I instantiate a `marqo.NewClient()`?

**Comment by brianfeister** [comment]
I see you're using `imroc/req/v3` for req middleware handling, but haven't quite figured out how to implement it's `SetCommonBearerAuthToken` method from my application code

**Comment by ganeshdipdumbare** [comment]
@brianfeister Thanks for pointing out. I believe you can create PR to add  the option and new field in the client then. Something similar to logger - 
https://github.com/ganeshdipdumbare/marqo-go/blob/main/client.go#L19

**Comment by brianfeister** [comment]
@ganeshdipdumbare thanks for getting back to me! I'll submit a PR soon to add this, thanks so much!

**Comment by brianfeister** [comment]
@ganeshdipdumbare am I wrong when I see a concern that `opt ...Options` is applied prior to the `client.reqClient = req.NewClient()` instance?

Seems like `WithBearerToken()` wants the for loop to run after, while `WithLogger()` wants it to run before... an example from my tinkering:

```
func WithBearerToken(bearerToken string) func(*Client) {
	return func(c *Client) {
		c.reqClient.SetCommonBearerAuthToken(bearerToken)
	}
}

// Client is the client for the marqo server
type Client struct {
	url       string
	logger    *slog.Logger
	reqClient *req.Client
}

// NewClient creates a new client
func NewClient(url string, opt ...Options) (*Client, error) {
	if url == "" {
		return nil, fmt.Errorf("url cannot be empty")
	}

	client := &Client{
		url: url,
	}

	for _, o := range opt {
		o(client)
	}

	// set req client
	if client.reqClient == nil {
		client.reqClient = req.NewClient()
		client.reqClient.BaseURL = url
	}

```

**Comment by ganeshdipdumbare** [comment]
@brianfeister I mean something like this - 

```
func WithBearerToken(bearerToken string) func(*Client) {
	return func(c *Client) {
		c.bearerToken = bearerToken
	}
}

// Client is the client for the marqo server
type Client struct {
	url       string
	logger    *slog.Logger
	reqClient *req.Client
        bearerToken string
}

// NewClient creates a new client
func NewClient(url string, opt ...Options) (*Client, error) {
	if url == "" {
		return nil, fmt.Errorf("url cannot be empty")
	}

	client := &Client{
		url: url,
	}

	for _, o := range opt {
		o(client)
	}

	// set req client
	if client.reqClient == nil {
		client.reqClient = req.NewClient()
		client.reqClient.BaseURL = url
	}
         // check if bearer token is not empty, set default header for the client here
        if client.bearerToken!="" {
        // add code here...
        }
```

**Comment by msnorth** [comment]
like this? https://github.com/ganeshdipdumbare/marqo-go/pull/12

**Comment by ganeshdipdumbare** [comment]
@brianfeister Fixed by @msnorth. Please let me know if this works for you. Closing the issue for now.
